name: gesturedeck_flutter_example
description: Demonstrates how to use the gesturedeck_flutter plugin.
version: 0.0.1+1
publish_to: "none"

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gesturedeck_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: assets/icon.jpg
  ios: true
  remove_alpha_ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/