// Autogenerated from Pigeon (v10.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct OverlayConfig {
  var tintColor: String? = nil
  var overlayBackgroundColor: String? = nil
  var topIcon: FlutterStandardTypedData? = nil
  var iconSwipeLeft: FlutterStandardTypedData? = nil
  var iconSwipeRight: FlutterStandardTypedData? = nil
  var iconTap: FlutterStandardTypedData? = nil
  var iconTapToggled: FlutterStandardTypedData? = nil

  static func fromList(_ list: [Any?]) -> OverlayConfig? {
    let tintColor: String? = nilOrValue(list[0])
    let overlayBackgroundColor: String? = nilOrValue(list[1])
    let topIcon: FlutterStandardTypedData? = nilOrValue(list[2])
    let iconSwipeLeft: FlutterStandardTypedData? = nilOrValue(list[3])
    let iconSwipeRight: FlutterStandardTypedData? = nilOrValue(list[4])
    let iconTap: FlutterStandardTypedData? = nilOrValue(list[5])
    let iconTapToggled: FlutterStandardTypedData? = nilOrValue(list[6])

    return OverlayConfig(
      tintColor: tintColor,
      overlayBackgroundColor: overlayBackgroundColor,
      topIcon: topIcon,
      iconSwipeLeft: iconSwipeLeft,
      iconSwipeRight: iconSwipeRight,
      iconTap: iconTap,
      iconTapToggled: iconTapToggled
    )
  }
  func toList() -> [Any?] {
    return [
      tintColor,
      overlayBackgroundColor,
      topIcon,
      iconSwipeLeft,
      iconSwipeRight,
      iconTap,
      iconTapToggled,
    ]
  }
}
/// Gesturedeck
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol GesturedeckChannel {
  func initialize(androidActivationKey: String?, iosActivationKey: String?, autoStart: Bool) throws
  func start() throws
  func stop() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class GesturedeckChannelSetup {
  /// The codec used by GesturedeckChannel.
  /// Sets up an instance of `GesturedeckChannel` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: GesturedeckChannel?) {
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckChannel.initialize", binaryMessenger: binaryMessenger)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let androidActivationKeyArg: String? = nilOrValue(args[0])
        let iosActivationKeyArg: String? = nilOrValue(args[1])
        let autoStartArg = args[2] as! Bool
        do {
          try api.initialize(androidActivationKey: androidActivationKeyArg, iosActivationKey: iosActivationKeyArg, autoStart: autoStartArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckChannel.start", binaryMessenger: binaryMessenger)
    if let api = api {
      startChannel.setMessageHandler { _, reply in
        do {
          try api.start()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckChannel.stop", binaryMessenger: binaryMessenger)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
  }
}
private class GesturedeckMediaChannelCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return OverlayConfig.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class GesturedeckMediaChannelCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? OverlayConfig {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class GesturedeckMediaChannelCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return GesturedeckMediaChannelCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return GesturedeckMediaChannelCodecWriter(data: data)
  }
}

class GesturedeckMediaChannelCodec: FlutterStandardMessageCodec {
  static let shared = GesturedeckMediaChannelCodec(readerWriter: GesturedeckMediaChannelCodecReaderWriter())
}

/// GesturedeckMedia
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol GesturedeckMediaChannel {
  func initialize(androidActivationKey: String?, iosActivationKey: String?, autoStart: Bool, reverseHorizontalSwipes: Bool, panSensitivity: Int64?, overlayConfig: OverlayConfig?) throws
  func start() throws
  func stop() throws
  func dispose() throws
  func reverseHorizontalSwipes(value: Bool) throws
  func setGesturedeckMediaOverlay(overlayConfig: OverlayConfig?) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class GesturedeckMediaChannelSetup {
  /// The codec used by GesturedeckMediaChannel.
  static var codec: FlutterStandardMessageCodec { GesturedeckMediaChannelCodec.shared }
  /// Sets up an instance of `GesturedeckMediaChannel` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: GesturedeckMediaChannel?) {
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckMediaChannel.initialize", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let androidActivationKeyArg: String? = nilOrValue(args[0])
        let iosActivationKeyArg: String? = nilOrValue(args[1])
        let autoStartArg = args[2] as! Bool
        let reverseHorizontalSwipesArg = args[3] as! Bool
        let panSensitivityArg: Int64? = args[4] is NSNull ? nil : (args[4] is Int64? ? args[4] as! Int64? : Int64(args[4] as! Int32))
        let overlayConfigArg: OverlayConfig? = nilOrValue(args[5])
        do {
          try api.initialize(androidActivationKey: androidActivationKeyArg, iosActivationKey: iosActivationKeyArg, autoStart: autoStartArg, reverseHorizontalSwipes: reverseHorizontalSwipesArg, panSensitivity: panSensitivityArg, overlayConfig: overlayConfigArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckMediaChannel.start", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { _, reply in
        do {
          try api.start()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckMediaChannel.stop", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckMediaChannel.dispose", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let reverseHorizontalSwipesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckMediaChannel.reverseHorizontalSwipes", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reverseHorizontalSwipesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Bool
        do {
          try api.reverseHorizontalSwipes(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      reverseHorizontalSwipesChannel.setMessageHandler(nil)
    }
    let setGesturedeckMediaOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckMediaChannel.setGesturedeckMediaOverlay", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setGesturedeckMediaOverlayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let overlayConfigArg: OverlayConfig? = nilOrValue(args[0])
        do {
          try api.setGesturedeckMediaOverlay(overlayConfig: overlayConfigArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setGesturedeckMediaOverlayChannel.setMessageHandler(nil)
    }
  }
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class GesturedeckCallback {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  func onTap(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckCallback.onTap", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  func onSwipeLeft(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckCallback.onSwipeLeft", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  func onSwipeRight(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckCallback.onSwipeRight", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  func onPan(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckCallback.onPan", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  func onLongPress(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckCallback.onLongPress", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class GesturedeckMediaCallback {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  func onTap(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckMediaCallback.onTap", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  func onSwipeLeft(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckMediaCallback.onSwipeLeft", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  func onSwipeRight(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckMediaCallback.onSwipeRight", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  func onPan(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckMediaCallback.onPan", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
  func onLongPress(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gesturedeck_flutter.GesturedeckMediaCallback.onLongPress", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
}
